import os
import re
from datetime import datetime
import re

def process_images():
    """
    Process DALL·E images in the specified directory.

    This function reads the image files in the './images' directory, extracts
    relevant information from the filenames using regular expressions, and
    renames the files based on the extracted data. It also stores the extracted
    data in a list of dictionaries.

    Returns:
        extracted_data (list): A list of dictionaries containing the extracted
        data from the image filenames. Each dictionary has the following keys:
            - 'generated_by': The first 6 characters of the 'llm_prompt' string.
            - 'date_generated': A datetime object representing the date and time
              extracted from the filename.
            - 'llm_prompt': The full 'llm_prompt' string extracted from the filename.
    """
    image_dir = "./images"
    image_files = os.listdir(image_dir)

    extracted_data = []

    for image_file in image_files:

# take this format "images\DALL·E 2023-12-16 15.36.18 - Create an image of a futuristic cloning machine in a cozy living room. The machine is duplicating a small, detailed model of a server, symbolizing the.png"
# and extract the generated_by "DALL·E" and date_generated "2023-12-16 15.36.18" and llm_prompt "Create an image of a futuristic cloning machine in a cozy living room. The machine is duplicating a small, detailed model of a server, symbolizing the"
            # ...

            for image_file in image_files:
                match = re.match(r".*DALL·E (\d{4}-\d{2}-\d{2} \d{2}\.\d{2}\.\d{2}) - (.*)\.png", image_file)
                if match:
                    # extract generated_by using the first characters up to the first "-"" 
                    #before the date in the example image name "DALL·E 2023-12-16 15.36.18 - Create an image.png" generated_by would be "DALL·E"
                    generated_by = image_file.split("-")[0].strip()
                    # extract date_generated using the regex match in example "DALL·E 2023-12-16 15.36.18 - Create an image.png" date_generated would be "2023-12-16 15.36.18"
                    date_generated = datetime.strptime(match.group(1), "%Y-%m-%d %H.%M.%S")
                    # extract llm_prompt using the regex match in example "DALL·E 2023-12-16 15.36.18 - Create an image.png" llm_prompt would be "Create an image"
                    llm_prompt = match.group(2)
                    
                    # Storing extracted data as a csv file to my prompts folder 
                        
                    with open("./prompts/extracted_data.csv", "a") as f:
                        f.write(f"{generated_by},{date_generated},{llm_prompt}\n")

                    extracted_data.append({
                        "generated_by": generated_by,
                        "date_generated": date_generated,
                        "llm_prompt": llm_prompt
                    })

            # Generating a new, shorter filename
            new_file_name = f"{generated_by}_{date_generated.strftime('%Y%m%d%H%M%S')}.png"
            os.rename(os.path.join(image_dir, image_file), os.path.join(image_dir, new_file_name))

    return extracted_data

# Printing the extracted data
extracted_data = process_images()
print(extracted_data)
for data in extracted_data:
    print(f"Generated By: {data['generated_by']}, Generated Date: {data['date_generated']}, LLM Prompt: {data['llm_prompt']}")
