import os
import re
from datetime import datetime

image_dir = "./images"
image_files = os.listdir(image_dir)

# Sort the image files based on their creation time
image_files.sort(key=lambda x: os.path.getctime(os.path.join(image_dir, x)))

for image_file in image_files:
    # Extract the information from the image title
    match = re.match(r"DALL·E (\d{4}-\d{2}-\d{2} \d{2}.\d{2}.\d{2}) - (.+)\.png", image_file)
    if match:
        generated_date = datetime.strptime(match.group(1), "%Y-%m-%d %H.%M.%S")
        generated_by = match.group(2)
        llm_prompt = generated_by.split(" - ")[-1]

        # Rename the image file
        new_file_name = f"{generated_by} - {generated_date.strftime('%Y%m%d%H%M%S')} - {llm_prompt}.png"
        os.rename(os.path.join(image_dir, image_file), os.path.join(image_dir, new_file_name))

        # Print the extracted information
        print(f"Image Name: {new_file_name}")
        print(f"Generated By: {generated_by}")
        print(f"Generated Date: {generated_date}")
        print(f"LLM Prompt: {llm_prompt}")
