import os
import re
from datetime import datetime

def process_images():
    """
    Process DALL·E images in the specified directory.

    This function reads the image files in the './images' directory, extracts
    relevant information from the filenames using regular expressions, and
    renames the files based on the extracted data. It also stores the extracted
    data in a list of dictionaries.

    Returns:
        extracted_data (list): A list of dictionaries containing the extracted
        data from the image filenames. Each dictionary has the following keys:
            - 'generated_by': The first 6 characters of the 'llm_prompt' string.
            - 'date_generated': A datetime object representing the date and time
              extracted from the filename.
            - 'llm_prompt': The full 'llm_prompt' string extracted from the filename.
    """
    image_dir = "./images"
    image_files = os.listdir(image_dir)

    extracted_data = []

    for image_file in image_files:
        # Regular expression to parse the filename
        match = re.match(r"DALL·E (\d{4}-\d{2}-\d{2} \d{2}.\d{2}.\d{2}) - (.+)\.png", image_file)
        if match:
            date_generated = datetime.strptime(match.group(1), "%Y-%m-%d %H.%M.%S")
            llm_prompt = match.group(2)

            # Extracting first 6 characters for 'generated_by'
            generated_by = llm_prompt[:6]

            # Storing extracted data
            extracted_data.append({
                "generated_by": generated_by,
                "date_generated": date_generated,
                "llm_prompt": llm_prompt
            })

            # Generating a new, shorter filename
            new_file_name = f"{generated_by}_{date_generated.strftime('%Y%m%d%H%M%S')}.png"
            os.rename(os.path.join(image_dir, image_file), os.path.join(image_dir, new_file_name))

    return extracted_data

# Printing the extracted data
print(process_images())
for data in extracted_data:
    print(f"Generated By: {data['generated_by']}, Generated Date: {data['date_generated']}, LLM Prompt: {data['llm_prompt']}")
